// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Item in *Article → Tags*
 */
export interface ArticleDocumentDataTagsItem {
  /**
   * Tag field in *Article → Tags*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: article.tags[].tag
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  tag: prismic.ContentRelationshipField<"tag">;
}

type ArticleDocumentDataSlicesSlice = never;

/**
 * Content for Article documents
 */
interface ArticleDocumentData {
  /**
   * Title field in *Article*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Заголовок статьи
   * - **API ID Path**: article.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Description field in *Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Краткое описание
   * - **API ID Path**: article.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * Date field in *Article*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: article.date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  date: prismic.DateField;

  /**
   * Author field in *Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Имя автора
   * - **API ID Path**: article.author
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  author: prismic.KeyTextField;

  /**
   * Featured field in *Article*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: Отметить как главную
   * - **API ID Path**: article.featured
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  featured: prismic.BooleanField;

  /**
   * Tags field in *Article*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: article.tags[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  tags: prismic.GroupField<Simplify<ArticleDocumentDataTagsItem>>;

  /**
   * Content field in *Article*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Основной текст статьи
   * - **API ID Path**: article.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;

  /**
   * Slice Zone field in *Article*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: article.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<ArticleDocumentDataSlicesSlice>; /**
   * Meta Title field in *Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: article.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: article.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Article*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: article.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Article document from Prismic
 *
 * - **API ID**: `article`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ArticleDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ArticleDocumentData>,
    "article",
    Lang
  >;

type ArticlelandingpageDocumentDataSlicesSlice =
  | FormSlice
  | NoteBannerSlice
  | InfoCardSlice
  | ValuesBlockSlice
  | QaSlice
  | BigEventSlice
  | LandingPageHeroSlice
  | BannerSlice
  | SubscribeToNewsletterSlice;

/**
 * Content for ArticleLandingPage documents
 */
interface ArticlelandingpageDocumentData {
  /**
   * Slice Zone field in *ArticleLandingPage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: articlelandingpage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<ArticlelandingpageDocumentDataSlicesSlice>; /**
   * Meta Title field in *ArticleLandingPage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: articlelandingpage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *ArticleLandingPage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: articlelandingpage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *ArticleLandingPage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: articlelandingpage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * ArticleLandingPage document from Prismic
 *
 * - **API ID**: `articlelandingpage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ArticlelandingpageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ArticlelandingpageDocumentData>,
    "articlelandingpage",
    Lang
  >;

/**
 * Content for Author documents
 */
interface AuthorDocumentData {
  /**
   * Name field in *Author*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Display name
   * - **API ID Path**: author.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Profile page (optional) field in *Author*
   *
   * - **Field Type**: Link
   * - **Placeholder**: https://...
   * - **API ID Path**: author.page
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  page: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Author document from Prismic
 *
 * - **API ID**: `author`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AuthorDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<AuthorDocumentData>, "author", Lang>;

/**
 * Item in *Book → Tags (optional)*
 */
export interface BookDocumentDataTagsItem {
  /**
   * Tag field in *Book → Tags (optional)*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: book.tags[].tag
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  tag: prismic.ContentRelationshipField<"tag">;
}

/**
 * Content for Book documents
 */
interface BookDocumentData {
  /**
   * Image field in *Book*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: book.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *Book*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Book title
   * - **API ID Path**: book.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Description field in *Book*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Short description
   * - **API ID Path**: book.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * Tags (optional) field in *Book*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: book.tags[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  tags: prismic.GroupField<Simplify<BookDocumentDataTagsItem>>;

  /**
   * Year of Release field in *Book*
   *
   * - **Field Type**: Number
   * - **Placeholder**: 2026
   * - **API ID Path**: book.date_of_release
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  date_of_release: prismic.NumberField;

  /**
   * Author field in *Book*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Author name
   * - **API ID Path**: book.author
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  author: prismic.KeyTextField;

  /**
   * Buy Link field in *Book*
   *
   * - **Field Type**: Link
   * - **Placeholder**: https://...
   * - **API ID Path**: book.buy_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  buy_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Featured field in *Book*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: book.featured
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  featured: prismic.BooleanField;
}

/**
 * Book document from Prismic
 *
 * - **API ID**: `book`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BookDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<BookDocumentData>, "book", Lang>;

type BooklandingpageDocumentDataSlicesSlice =
  | FormSlice
  | CardSlice
  | LandingPageHeroSlice
  | BannerSlice
  | SubscribeToNewsletterSlice
  | QaSlice
  | ValuesBlockSlice
  | NoteBannerSlice
  | InfoCardSlice;

/**
 * Content for BookLandingPage documents
 */
interface BooklandingpageDocumentData {
  /**
   * Slice Zone field in *BookLandingPage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: booklandingpage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<BooklandingpageDocumentDataSlicesSlice>; /**
   * Meta Title field in *BookLandingPage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: booklandingpage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *BookLandingPage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: booklandingpage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *BookLandingPage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: booklandingpage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * BookLandingPage document from Prismic
 *
 * - **API ID**: `booklandingpage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BooklandingpageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<BooklandingpageDocumentData>,
    "booklandingpage",
    Lang
  >;

type CommunityDocumentDataSlicesSlice =
  | BigEventSlice
  | FormSlice
  | CardSlice
  | BannerSlice
  | SubscribeToNewsletterSlice
  | ValuesBlockSlice
  | QaSlice
  | InfoCardSlice
  | NoteBannerSlice;

/**
 * Content for Community documents
 */
interface CommunityDocumentData {
  /**
   * Image field in *Community*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: community.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *Community*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Название общины
   * - **API ID Path**: community.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Description field in *Community*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Краткое описание
   * - **API ID Path**: community.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Address field in *Community*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Адрес
   * - **API ID Path**: community.address
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  address: prismic.KeyTextField;

  /**
   * Leader field in *Community*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Лидер
   * - **API ID Path**: community.leader
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  leader: prismic.KeyTextField;

  /**
   * Service Time field in *Community*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Служение
   * - **API ID Path**: community.service_time
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  service_time: prismic.KeyTextField;

  /**
   * Button 1 Link field in *Community*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link for the first optional button
   * - **API ID Path**: community.button_1_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button_1_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    "Primary" | "Secondary"
  >;

  /**
   * Button 2 Link field in *Community*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link for the second optional button
   * - **API ID Path**: community.button_2_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button_2_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    "Primary" | "Secondary"
  >;

  /**
   * Slice Zone field in *Community*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: community.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<CommunityDocumentDataSlicesSlice>; /**
   * Meta Title field in *Community*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: community.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Community*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: community.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Community*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: community.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Community document from Prismic
 *
 * - **API ID**: `community`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CommunityDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CommunityDocumentData>,
    "community",
    Lang
  >;

type CommunitylandingpageDocumentDataSlicesSlice =
  | BigEventSlice
  | FormSlice
  | CardSlice
  | LandingPageHeroSlice
  | BannerSlice
  | SubscribeToNewsletterSlice
  | ValuesBlockSlice
  | QaSlice
  | InfoCardSlice
  | NoteBannerSlice;

/**
 * Content for CommunityLandingPage documents
 */
interface CommunitylandingpageDocumentData {
  /**
   * Image field in *CommunityLandingPage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: communitylandingpage.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *CommunityLandingPage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Название общины
   * - **API ID Path**: communitylandingpage.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Description field in *CommunityLandingPage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Краткое описание
   * - **API ID Path**: communitylandingpage.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * Button 1 Link field in *CommunityLandingPage*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link for the first optional button
   * - **API ID Path**: communitylandingpage.button_1_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button_1_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    "Primary" | "Secondary"
  >;

  /**
   * Button 2 Link field in *CommunityLandingPage*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link for the second optional button
   * - **API ID Path**: communitylandingpage.button_2_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button_2_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    "Primary" | "Secondary"
  >;

  /**
   * Slice Zone field in *CommunityLandingPage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: communitylandingpage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<CommunitylandingpageDocumentDataSlicesSlice>; /**
   * Meta Title field in *CommunityLandingPage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: communitylandingpage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *CommunityLandingPage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: communitylandingpage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *CommunityLandingPage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: communitylandingpage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * CommunityLandingPage document from Prismic
 *
 * - **API ID**: `communitylandingpage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CommunitylandingpageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CommunitylandingpageDocumentData>,
    "communitylandingpage",
    Lang
  >;

/**
 * Item in *Footer → Navigation links*
 */
export interface FooterDocumentDataNavigationLinksItem {
  /**
   * Label field in *Footer → Navigation links*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Link label
   * - **API ID Path**: footer.navigation_links[].label
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  label: prismic.RichTextField;

  /**
   * Link field in *Footer → Navigation links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link URL
   * - **API ID Path**: footer.navigation_links[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Item in *Footer → Action links*
 */
export interface FooterDocumentDataActionLinksItem {
  /**
   * Label field in *Footer → Action links*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Link label
   * - **API ID Path**: footer.action_links[].label
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  label: prismic.RichTextField;

  /**
   * Link field in *Footer → Action links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link URL
   * - **API ID Path**: footer.action_links[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Item in *Footer → Service times*
 */
export interface FooterDocumentDataServiceTimesItem {
  /**
   * Label field in *Footer → Service times*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Sunday worship
   * - **API ID Path**: footer.service_times[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Time field in *Footer → Service times*
   *
   * - **Field Type**: Text
   * - **Placeholder**: 10:00
   * - **API ID Path**: footer.service_times[].time
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  time: prismic.KeyTextField;
}

/**
 * Item in *Footer → Social links*
 */
export interface FooterDocumentDataSocialLinksItem {
  /**
   * Label field in *Footer → Social links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: YouTube
   * - **API ID Path**: footer.social_links[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *Footer → Social links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: https://...
   * - **API ID Path**: footer.social_links[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * Logo field in *Footer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;

  /**
   * Address line 1 field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Street address
   * - **API ID Path**: footer.address_line_1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  address_line_1: prismic.KeyTextField;

  /**
   * Address line 2 field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: City, region, postal code
   * - **API ID Path**: footer.address_line_2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  address_line_2: prismic.KeyTextField;

  /**
   * Email field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: hello@example.com
   * - **API ID Path**: footer.email
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  email: prismic.KeyTextField;

  /**
   * Phone field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: +1 555 123 4567
   * - **API ID Path**: footer.phone
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  phone: prismic.KeyTextField;

  /**
   * Navigation column title field in *Footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Navigation
   * - **API ID Path**: footer.navigation_column_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  navigation_column_title: prismic.RichTextField;

  /**
   * Navigation links field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.navigation_links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  navigation_links: prismic.GroupField<
    Simplify<FooterDocumentDataNavigationLinksItem>
  >;

  /**
   * Actions column title field in *Footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Next steps
   * - **API ID Path**: footer.actions_column_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  actions_column_title: prismic.RichTextField;

  /**
   * Action links field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.action_links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  action_links: prismic.GroupField<Simplify<FooterDocumentDataActionLinksItem>>;

  /**
   * Service times title field in *Footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Service times
   * - **API ID Path**: footer.service_times_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  service_times_title: prismic.RichTextField;

  /**
   * Service times field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.service_times[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  service_times: prismic.GroupField<
    Simplify<FooterDocumentDataServiceTimesItem>
  >;

  /**
   * Social links field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.social_links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  social_links: prismic.GroupField<Simplify<FooterDocumentDataSocialLinksItem>>;

  /**
   * Copyright text field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: © 2026 AMJRC. Все права защищены.
   * - **API ID Path**: footer.copyright_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  copyright_text: prismic.KeyTextField;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

type HomeDocumentDataSlicesSlice =
  | ValuesBlockSlice
  | SubscribeToNewsletterSlice
  | NoteBannerSlice
  | QaSlice
  | InfoCardSlice
  | CardSlice
  | BigEventSlice
  | HeroSlice
  | FormSlice
  | BannerSlice;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice>; /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

type LandingpageDocumentDataSlicesSlice =
  | TeamSectionSlice
  | HistoryEventsSlice
  | InfoCardSlice
  | QaSlice
  | SubscribeToNewsletterSlice
  | ValuesBlockSlice
  | FormSlice
  | BannerSlice
  | BigEventSlice
  | CardSlice
  | LandingPageHeroSlice
  | NoteBannerSlice;

/**
 * Content for LandingPage documents
 */
interface LandingpageDocumentData {
  /**
   * Image field in *LandingPage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: landingpage.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *LandingPage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Заголовок страницы
   * - **API ID Path**: landingpage.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Description field in *LandingPage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Краткое описание
   * - **API ID Path**: landingpage.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Button 1 Link field in *LandingPage*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link for the first optional button
   * - **API ID Path**: landingpage.button_1_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button_1_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    "Primary" | "Secondary"
  >;

  /**
   * Button 2 Link field in *LandingPage*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link for the second optional button
   * - **API ID Path**: landingpage.button_2_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button_2_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    "Primary" | "Secondary"
  >;

  /**
   * Slice Zone field in *LandingPage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: landingpage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<LandingpageDocumentDataSlicesSlice>; /**
   * Meta Title field in *LandingPage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: landingpage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *LandingPage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: landingpage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *LandingPage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: landingpage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * LandingPage document from Prismic
 *
 * - **API ID**: `landingpage`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LandingpageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<LandingpageDocumentData>,
    "landingpage",
    Lang
  >;

/**
 * Item in *Header → Dropdown items*
 */
export interface NavigationDocumentDataDropdownItemsItem {
  /**
   * Link field in *Header → Dropdown items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link for dropdown item
   * - **API ID Path**: navigation.dropdown_items[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Icon field in *Header → Dropdown items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Select an icon
   * - **API ID Path**: navigation.dropdown_items[].icon
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  icon: prismic.SelectField<
    "Video" | "Mic" | "FileText" | "BookMarked" | "Radio" | "Newspaper"
  >;
}

/**
 * Content for Header documents
 */
interface NavigationDocumentData {
  /**
   * Logo field in *Header*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;

  /**
   * Dropdown label field in *Header*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Optional - Label for the dropdown
   * - **API ID Path**: navigation.dropdown_label
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  dropdown_label: prismic.RichTextField;

  /**
   * Nav field in *Header*
   *
   * - **Field Type**: Link
   * - **Placeholder**: nav
   * - **API ID Path**: navigation.nav
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  nav: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * Dropdown link field in *Header*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link for the dropdown
   * - **API ID Path**: navigation.dropdown_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  dropdown_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Dropdown items field in *Header*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.dropdown_items[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  dropdown_items: prismic.GroupField<
    Simplify<NavigationDocumentDataDropdownItemsItem>
  >;

  /**
   * Primary button link field in *Header*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link for primary action
   * - **API ID Path**: navigation.action_button_primary_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  action_button_primary_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    "Primary" | "Secondary"
  >;

  /**
   * Secondary button link field in *Header*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link for secondary action
   * - **API ID Path**: navigation.action_button_secondary_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  action_button_secondary_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    "Primary" | "Secondary"
  >;
}

/**
 * Header document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavigationDocumentData>,
    "navigation",
    Lang
  >;

/**
 * Item in *Newspaper → Tags (optional)*
 */
export interface NewspaperDocumentDataTagsItem {
  /**
   * Tag field in *Newspaper → Tags (optional)*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: newspaper.tags[].tag
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  tag: prismic.ContentRelationshipField<"tag">;
}

/**
 * Content for Newspaper documents
 */
interface NewspaperDocumentData {
  /**
   * Title field in *Newspaper*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Newspaper title
   * - **API ID Path**: newspaper.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Description field in *Newspaper*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Short description
   * - **API ID Path**: newspaper.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * PDF field in *Newspaper*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: newspaper.pdf
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  pdf: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * Author (optional) field in *Newspaper*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Author name
   * - **API ID Path**: newspaper.author
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  author: prismic.KeyTextField;

  /**
   * Featured field in *Newspaper*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: newspaper.featured
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  featured: prismic.BooleanField;

  /**
   * Tags (optional) field in *Newspaper*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: newspaper.tags[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  tags: prismic.GroupField<Simplify<NewspaperDocumentDataTagsItem>>;
}

/**
 * Newspaper document from Prismic
 *
 * - **API ID**: `newspaper`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NewspaperDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<NewspaperDocumentData>,
    "newspaper",
    Lang
  >;

type NewspaperlandingpageDocumentDataSlicesSlice =
  | LandingPageHeroSlice
  | FormSlice
  | CardSlice
  | ValuesBlockSlice
  | SubscribeToNewsletterSlice
  | BannerSlice
  | QaSlice
  | InfoCardSlice
  | NoteBannerSlice;

/**
 * Content for NewspaperLandingPage documents
 */
interface NewspaperlandingpageDocumentData {
  /**
   * Slice Zone field in *NewspaperLandingPage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: newspaperlandingpage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<NewspaperlandingpageDocumentDataSlicesSlice>; /**
   * Meta Title field in *NewspaperLandingPage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: newspaperlandingpage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *NewspaperLandingPage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: newspaperlandingpage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *NewspaperLandingPage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: newspaperlandingpage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * NewspaperLandingPage document from Prismic
 *
 * - **API ID**: `newspaperlandingpage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NewspaperlandingpageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NewspaperlandingpageDocumentData>,
    "newspaperlandingpage",
    Lang
  >;

/**
 * Item in *Podcast → Tags*
 */
export interface PodcastDocumentDataTagsItem {
  /**
   * Tag field in *Podcast → Tags*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: podcast.tags[].tag
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  tag: prismic.ContentRelationshipField<"tag">;
}

/**
 * Content for Podcast documents
 */
interface PodcastDocumentData {
  /**
   * Title field in *Podcast*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Название выпуска
   * - **API ID Path**: podcast.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Description field in *Podcast*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Краткое описание
   * - **API ID Path**: podcast.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * Date field in *Podcast*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: podcast.date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  date: prismic.DateField;

  /**
   * Author field in *Podcast*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Имя ведущего или гостя
   * - **API ID Path**: podcast.author
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  author: prismic.KeyTextField;

  /**
   * Ссылка на выпуск (Spotify/Apple/др.) field in *Podcast*
   *
   * - **Field Type**: Link
   * - **Placeholder**: https://open.spotify.com/...
   * - **API ID Path**: podcast.external_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  external_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Featured field in *Podcast*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: Отметить как главный выпуск
   * - **API ID Path**: podcast.featured
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  featured: prismic.BooleanField;

  /**
   * Tags field in *Podcast*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: podcast.tags[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  tags: prismic.GroupField<Simplify<PodcastDocumentDataTagsItem>>; /**
   * Meta Title field in *Podcast*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: podcast.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Podcast*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: podcast.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Podcast*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: podcast.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Podcast document from Prismic
 *
 * - **API ID**: `podcast`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PodcastDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<PodcastDocumentData>,
    "podcast",
    Lang
  >;

type PodcastlandingpageDocumentDataSlicesSlice =
  | FormSlice
  | CardSlice
  | LandingPageHeroSlice
  | BannerSlice
  | NoteBannerSlice
  | SubscribeToNewsletterSlice
  | ValuesBlockSlice
  | QaSlice
  | InfoCardSlice;

/**
 * Content for PodcastLandingPage documents
 */
interface PodcastlandingpageDocumentData {
  /**
   * Slice Zone field in *PodcastLandingPage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: podcastlandingpage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PodcastlandingpageDocumentDataSlicesSlice>; /**
   * Meta Title field in *PodcastLandingPage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: podcastlandingpage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *PodcastLandingPage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: podcastlandingpage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *PodcastLandingPage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: podcastlandingpage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * PodcastLandingPage document from Prismic
 *
 * - **API ID**: `podcastlandingpage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PodcastlandingpageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<PodcastlandingpageDocumentData>,
    "podcastlandingpage",
    Lang
  >;

/**
 * Content for Tag documents
 */
interface TagDocumentData {
  /**
   * Name field in *Tag*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Tag name
   * - **API ID Path**: tag.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;
}

/**
 * Tag document from Prismic
 *
 * - **API ID**: `tag`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TagDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<TagDocumentData>, "tag", Lang>;

type TorahlandingpageDocumentDataSlicesSlice = never;

/**
 * Content for TorahLandingPage documents
 */
interface TorahlandingpageDocumentData {
  /**
   * Slice Zone field in *TorahLandingPage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: torahlandingpage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<TorahlandingpageDocumentDataSlicesSlice>; /**
   * Meta Title field in *TorahLandingPage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: torahlandingpage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *TorahLandingPage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: torahlandingpage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *TorahLandingPage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: torahlandingpage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * TorahLandingPage document from Prismic
 *
 * - **API ID**: `torahlandingpage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TorahlandingpageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<TorahlandingpageDocumentData>,
    "torahlandingpage",
    Lang
  >;

/**
 * Item in *Video → Tags (optional)*
 */
export interface VideoDocumentDataTagsItem {
  /**
   * Tag field in *Video → Tags (optional)*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: video.tags[].tag
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  tag: prismic.ContentRelationshipField<"tag">;
}

/**
 * Content for Video documents
 */
interface VideoDocumentData {
  /**
   * Title field in *Video*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Video title
   * - **API ID Path**: video.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Video*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Short summary
   * - **API ID Path**: video.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * YouTube URL field in *Video*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: https://www.youtube.com/watch?v=...
   * - **API ID Path**: video.youtube_url
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/embed
   */
  youtube_url: prismic.EmbedField;

  /**
   * Publish date field in *Video*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: video.date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  date: prismic.DateField;

  /**
   * Author (optional) field in *Video*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Name
   * - **API ID Path**: video.author
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  author: prismic.KeyTextField;

  /**
   * Tags (optional) field in *Video*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: video.tags[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  tags: prismic.GroupField<Simplify<VideoDocumentDataTagsItem>>;

  /**
   * Featured field in *Video*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: Mark as featured
   * - **API ID Path**: video.featured
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  featured: prismic.BooleanField;
}

/**
 * Video document from Prismic
 *
 * - **API ID**: `video`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type VideoDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<VideoDocumentData>, "video", Lang>;

type VideolandingpageDocumentDataSlicesSlice =
  | CardSlice
  | BannerSlice
  | SubscribeToNewsletterSlice
  | ValuesBlockSlice
  | NoteBannerSlice
  | QaSlice
  | InfoCardSlice
  | LandingPageHeroSlice;

/**
 * Content for VideoLandingPage documents
 */
interface VideolandingpageDocumentData {
  /**
   * Slice Zone field in *VideoLandingPage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: videolandingpage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<VideolandingpageDocumentDataSlicesSlice>; /**
   * Meta Title field in *VideoLandingPage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: videolandingpage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *VideoLandingPage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: videolandingpage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *VideoLandingPage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: videolandingpage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * VideoLandingPage document from Prismic
 *
 * - **API ID**: `videolandingpage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type VideolandingpageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<VideolandingpageDocumentData>,
    "videolandingpage",
    Lang
  >;

export type AllDocumentTypes =
  | ArticleDocument
  | ArticlelandingpageDocument
  | AuthorDocument
  | BookDocument
  | BooklandingpageDocument
  | CommunityDocument
  | CommunitylandingpageDocument
  | FooterDocument
  | HomeDocument
  | LandingpageDocument
  | NavigationDocument
  | NewspaperDocument
  | NewspaperlandingpageDocument
  | PodcastDocument
  | PodcastlandingpageDocument
  | TagDocument
  | TorahlandingpageDocument
  | VideoDocument
  | VideolandingpageDocument;

/**
 * Primary content in *Banner → Default → Primary*
 */
export interface BannerSliceDefaultPrimary {
  /**
   * Title field in *Banner → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Добро пожаловать
   * - **API ID Path**: banner.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Banner → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Короткое приглашение или сообщение
   * - **API ID Path**: banner.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * Button Link field in *Banner → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: https://example.com
   * - **API ID Path**: banner.default.primary.actionLink
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  actionLink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Background Image field in *Banner → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for Banner Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BannerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BannerSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Banner*
 */
type BannerSliceVariation = BannerSliceDefault;

/**
 * Banner Shared Slice
 *
 * - **API ID**: `banner`
 * - **Description**: Banner
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BannerSlice = prismic.SharedSlice<"banner", BannerSliceVariation>;

/**
 * Primary content in *BigEvent → Default → Primary*
 */
export interface BigEventSliceDefaultPrimary {
  /**
   * Label field in *BigEvent → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Следующее событие
   * - **API ID Path**: big_event.default.primary.label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Title field in *BigEvent → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Миссионерская конференция
   * - **API ID Path**: big_event.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Summary field in *BigEvent → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Короткое описание события
   * - **API ID Path**: big_event.default.primary.summary
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  summary: prismic.KeyTextField;

  /**
   * Date display field in *BigEvent → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: 25 апреля 2026
   * - **API ID Path**: big_event.default.primary.date
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  date: prismic.KeyTextField;

  /**
   * Time field in *BigEvent → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: 10:00
   * - **API ID Path**: big_event.default.primary.time
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  time: prismic.KeyTextField;

  /**
   * Location field in *BigEvent → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Москва, ул. Пример, 1
   * - **API ID Path**: big_event.default.primary.location
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  location: prismic.KeyTextField;

  /**
   * Countdown target field in *BigEvent → Default → Primary*
   *
   * - **Field Type**: Timestamp
   * - **Placeholder**: 2026-04-25T10:00:00+03:00
   * - **API ID Path**: big_event.default.primary.countdownTarget
   * - **Documentation**: https://prismic.io/docs/fields/timestamp
   */
  countdownTarget: prismic.TimestampField;

  /**
   * Background image field in *BigEvent → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: big_event.default.primary.backgroundImage
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  backgroundImage: prismic.ImageField<never>;

  /**
   * Primary button text field in *BigEvent → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Зарегистрироваться
   * - **API ID Path**: big_event.default.primary.primaryButtonText
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  primaryButtonText: prismic.KeyTextField;

  /**
   * Primary button link field in *BigEvent → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: big_event.default.primary.primaryButtonLink
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  primaryButtonLink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Secondary button text field in *BigEvent → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Подробнее
   * - **API ID Path**: big_event.default.primary.secondaryButtonText
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  secondaryButtonText: prismic.KeyTextField;

  /**
   * Secondary button link field in *BigEvent → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: big_event.default.primary.secondaryButtonLink
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  secondaryButtonLink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for BigEvent Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BigEventSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BigEventSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BigEvent*
 */
type BigEventSliceVariation = BigEventSliceDefault;

/**
 * BigEvent Shared Slice
 *
 * - **API ID**: `big_event`
 * - **Description**: BigEvent
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BigEventSlice = prismic.SharedSlice<
  "big_event",
  BigEventSliceVariation
>;

/**
 * Primary content in *Card → Default → Primary*
 */
export interface CardSliceDefaultPrimary {
  /**
   * Label field in *Card → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Миссия
   * - **API ID Path**: card.default.primary.label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Title field in *Card → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Во что мы верим
   * - **API ID Path**: card.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Card → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Краткое описание блока
   * - **API ID Path**: card.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;
}

/**
 * Primary content in *Card → Items*
 */
export interface CardSliceDefaultItem {
  /**
   * Highlight text (optional) field in *Card → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Короткая цитата/выдержка
   * - **API ID Path**: card.items[].description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * Title field in *Card → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Заголовок карточки
   * - **API ID Path**: card.items[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Body field in *Card → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Основное описание
   * - **API ID Path**: card.items[].body
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  body: prismic.KeyTextField;

  /**
   * Image field in *Card → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: card.items[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Button link field in *Card → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: https://example.com
   * - **API ID Path**: card.items[].buttonLink
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  buttonLink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for Card Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CardSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CardSliceDefaultPrimary>,
  Simplify<CardSliceDefaultItem>
>;

/**
 * Slice variation for *Card*
 */
type CardSliceVariation = CardSliceDefault;

/**
 * Card Shared Slice
 *
 * - **API ID**: `card`
 * - **Description**: Card
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CardSlice = prismic.SharedSlice<"card", CardSliceVariation>;

/**
 * Default variation for Form Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FormSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Form*
 */
type FormSliceVariation = FormSliceDefault;

/**
 * Form Shared Slice
 *
 * - **API ID**: `form`
 * - **Description**: Form
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FormSlice = prismic.SharedSlice<"form", FormSliceVariation>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Title field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Text field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;

  /**
   * Button Link field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.buttonLink
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  buttonLink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Button Text field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.buttonText
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  buttonText: prismic.KeyTextField;

  /**
   * Secondary Button Link field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.secondaryButtonLink
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  secondaryButtonLink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Secondary Button Text field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.secondaryButtonText
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  secondaryButtonText: prismic.KeyTextField;

  /**
   * Video Embed field in *Hero → Default → Primary*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: YouTube/Vimeo embed
   * - **API ID Path**: hero.default.primary.videoEmbed
   * - **Documentation**: https://prismic.io/docs/fields/embed
   */
  videoEmbed: prismic.EmbedField;

  /**
   * Background Image field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.backgroundImage
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  backgroundImage: prismic.ImageField<never>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *HistoryEvents → Default → Primary*
 */
export interface HistoryEventsSliceDefaultPrimary {
  /**
   * Badge Text field in *HistoryEvents → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: История
   * - **API ID Path**: history_events.default.primary.badge_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  badge_text: prismic.KeyTextField;

  /**
   * Heading field in *HistoryEvents → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Наш путь
   * - **API ID Path**: history_events.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Description field in *HistoryEvents → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Альянс рождён...
   * - **API ID Path**: history_events.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;
}

/**
 * Primary content in *HistoryEvents → Items*
 */
export interface HistoryEventsSliceDefaultItem {
  /**
   * Year field in *HistoryEvents → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: 1991
   * - **API ID Path**: history_events.items[].year
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  year: prismic.KeyTextField;

  /**
   * Milestone Heading field in *HistoryEvents → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Зарождение движения
   * - **API ID Path**: history_events.items[].heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Milestone Text field in *HistoryEvents → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Основание первых...
   * - **API ID Path**: history_events.items[].text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  text: prismic.KeyTextField;
}

/**
 * Default variation for HistoryEvents Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HistoryEventsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HistoryEventsSliceDefaultPrimary>,
  Simplify<HistoryEventsSliceDefaultItem>
>;

/**
 * Slice variation for *HistoryEvents*
 */
type HistoryEventsSliceVariation = HistoryEventsSliceDefault;

/**
 * HistoryEvents Shared Slice
 *
 * - **API ID**: `history_events`
 * - **Description**: HistoryEvents
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HistoryEventsSlice = prismic.SharedSlice<
  "history_events",
  HistoryEventsSliceVariation
>;

/**
 * Primary content in *InfoCard → Items*
 */
export interface InfoCardSliceDefaultItem {
  /**
   * Icon field in *InfoCard → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: ✦
   * - **API ID Path**: info_card.items[].icon
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  icon: prismic.KeyTextField;

  /**
   * Title field in *InfoCard → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Заголовок
   * - **API ID Path**: info_card.items[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Text field in *InfoCard → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Краткое описание
   * - **API ID Path**: info_card.items[].text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  text: prismic.KeyTextField;

  /**
   * Button link field in *InfoCard → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: https://example.com
   * - **API ID Path**: info_card.items[].buttonLink
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  buttonLink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Button variant field in *InfoCard → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: secondary
   * - **API ID Path**: info_card.items[].buttonVariant
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  buttonVariant: prismic.SelectField<"secondary" | "ghost", "filled">;

  /**
   * Button target field in *InfoCard → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: _self
   * - **API ID Path**: info_card.items[].buttonTarget
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  buttonTarget: prismic.SelectField<"_self" | "_blank", "filled">;
}

/**
 * Default variation for InfoCard Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type InfoCardSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<InfoCardSliceDefaultItem>
>;

/**
 * Slice variation for *InfoCard*
 */
type InfoCardSliceVariation = InfoCardSliceDefault;

/**
 * InfoCard Shared Slice
 *
 * - **API ID**: `info_card`
 * - **Description**: InfoCard
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type InfoCardSlice = prismic.SharedSlice<
  "info_card",
  InfoCardSliceVariation
>;

/**
 * Primary content in *LandingPageHero → Default → Primary*
 */
export interface LandingPageHeroSliceDefaultPrimary {
  /**
   * Title field in *LandingPageHero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: О нас
   * - **API ID Path**: landing_page_hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *LandingPageHero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Краткое описание секции (Rich Text)
   * - **API ID Path**: landing_page_hero.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Background image field in *LandingPageHero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page_hero.default.primary.backgroundImage
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  backgroundImage: prismic.ImageField<never>;

  /**
   * Breadcrumb home label field in *LandingPageHero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Главная
   * - **API ID Path**: landing_page_hero.default.primary.breadcrumbHomeLabel
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  breadcrumbHomeLabel: prismic.KeyTextField;

  /**
   * Breadcrumb home link field in *LandingPageHero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: /
   * - **API ID Path**: landing_page_hero.default.primary.breadcrumbHomeLink
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  breadcrumbHomeLink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Breadcrumb current field in *LandingPageHero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: О нас
   * - **API ID Path**: landing_page_hero.default.primary.breadcrumbCurrent
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  breadcrumbCurrent: prismic.KeyTextField;

  /**
   * Button label (optional) field in *LandingPageHero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Подробнее
   * - **API ID Path**: landing_page_hero.default.primary.buttonLabel
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  buttonLabel: prismic.KeyTextField;

  /**
   * Button link (optional) field in *LandingPageHero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: https://example.com
   * - **API ID Path**: landing_page_hero.default.primary.buttonLink
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  buttonLink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for LandingPageHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LandingPageHeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LandingPageHeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *LandingPageHero*
 */
type LandingPageHeroSliceVariation = LandingPageHeroSliceDefault;

/**
 * LandingPageHero Shared Slice
 *
 * - **API ID**: `landing_page_hero`
 * - **Description**: LandingPageHero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LandingPageHeroSlice = prismic.SharedSlice<
  "landing_page_hero",
  LandingPageHeroSliceVariation
>;

/**
 * Primary content in *NoteBanner → Default → Primary*
 */
export interface NoteBannerSliceDefaultPrimary {
  /**
   * Label field in *NoteBanner → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Слово президента
   * - **API ID Path**: note_banner.default.primary.label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Name field in *NoteBanner → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: President name
   * - **API ID Path**: note_banner.default.primary.name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Title field in *NoteBanner → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: President title
   * - **API ID Path**: note_banner.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Photo field in *NoteBanner → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: note_banner.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Signature field in *NoteBanner → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Optional closing line
   * - **API ID Path**: note_banner.default.primary.signature
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  signature: prismic.KeyTextField;

  /**
   * Button Text field in *NoteBanner → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Read more
   * - **API ID Path**: note_banner.default.primary.buttonText
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  buttonText: prismic.KeyTextField;

  /**
   * Button Link field in *NoteBanner → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: note_banner.default.primary.buttonLink
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  buttonLink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *NoteBanner → Items*
 */
export interface NoteBannerSliceDefaultItem {
  /**
   * Paragraph field in *NoteBanner → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Message paragraph
   * - **API ID Path**: note_banner.items[].paragraph
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  paragraph: prismic.KeyTextField;
}

/**
 * Default variation for NoteBanner Slice
 *
 * - **API ID**: `default`
 * - **Description**: President note banner with portrait, message, and CTA
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type NoteBannerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NoteBannerSliceDefaultPrimary>,
  Simplify<NoteBannerSliceDefaultItem>
>;

/**
 * Slice variation for *NoteBanner*
 */
type NoteBannerSliceVariation = NoteBannerSliceDefault;

/**
 * NoteBanner Shared Slice
 *
 * - **API ID**: `note_banner`
 * - **Description**: NoteBanner
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type NoteBannerSlice = prismic.SharedSlice<
  "note_banner",
  NoteBannerSliceVariation
>;

/**
 * Primary content in *Qa → Default → Primary*
 */
export interface QaSliceDefaultPrimary {
  /**
   * Title field in *Qa → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Частые вопросы
   * - **API ID Path**: qa.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Qa → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Ответы на самые популярные вопросы
   * - **API ID Path**: qa.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;
}

/**
 * Primary content in *Qa → Items*
 */
export interface QaSliceDefaultItem {
  /**
   * Question field in *Qa → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Как проходит ваше служение?
   * - **API ID Path**: qa.items[].question
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  question: prismic.KeyTextField;

  /**
   * Answer field in *Qa → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Мы собираемся каждое воскресенье...
   * - **API ID Path**: qa.items[].answer
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  answer: prismic.KeyTextField;
}

/**
 * Default variation for Qa Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type QaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<QaSliceDefaultPrimary>,
  Simplify<QaSliceDefaultItem>
>;

/**
 * Slice variation for *Qa*
 */
type QaSliceVariation = QaSliceDefault;

/**
 * Qa Shared Slice
 *
 * - **API ID**: `qa`
 * - **Description**: Qa
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type QaSlice = prismic.SharedSlice<"qa", QaSliceVariation>;

/**
 * Primary content in *SubscribeToNewsletter → Default → Primary*
 */
export interface SubscribeToNewsletterSliceDefaultPrimary {
  /**
   * Title field in *SubscribeToNewsletter → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Подпишитесь на рассылку
   * - **API ID Path**: subscribe_to_newsletter.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *SubscribeToNewsletter → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Будьте в курсе наших последних новостей и событий...
   * - **API ID Path**: subscribe_to_newsletter.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * Background image field in *SubscribeToNewsletter → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: subscribe_to_newsletter.default.primary.backgroundImage
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  backgroundImage: prismic.ImageField<never>;

  /**
   * Button text field in *SubscribeToNewsletter → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Подписаться
   * - **API ID Path**: subscribe_to_newsletter.default.primary.buttonText
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  buttonText: prismic.KeyTextField;
}

/**
 * Default variation for SubscribeToNewsletter Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SubscribeToNewsletterSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SubscribeToNewsletterSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SubscribeToNewsletter*
 */
type SubscribeToNewsletterSliceVariation = SubscribeToNewsletterSliceDefault;

/**
 * SubscribeToNewsletter Shared Slice
 *
 * - **API ID**: `subscribe_to_newsletter`
 * - **Description**: SubscribeToNewsletter
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SubscribeToNewsletterSlice = prismic.SharedSlice<
  "subscribe_to_newsletter",
  SubscribeToNewsletterSliceVariation
>;

/**
 * Primary content in *TeamSection → Default → Primary*
 */
export interface TeamSectionSliceDefaultPrimary {
  /**
   * Badge field in *TeamSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Руководство
   * - **API ID Path**: team_section.default.primary.badge
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  badge: prismic.KeyTextField;

  /**
   * Heading field in *TeamSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Команда Альянса
   * - **API ID Path**: team_section.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Description field in *TeamSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Наша команда...
   * - **API ID Path**: team_section.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;
}

/**
 * Primary content in *TeamSection → Items*
 */
export interface TeamSectionSliceDefaultItem {
  /**
   * Role field in *TeamSection → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_section.items[].role
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  role: prismic.KeyTextField;

  /**
   * Name field in *TeamSection → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_section.items[].name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Description field in *TeamSection → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_section.items[].description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * Image field in *TeamSection → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: team_section.items[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Responsibilities field in *TeamSection → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_section.items[].responsibilities
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  responsibilities: prismic.KeyTextField;
}

/**
 * Default variation for TeamSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TeamSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TeamSectionSliceDefaultPrimary>,
  Simplify<TeamSectionSliceDefaultItem>
>;

/**
 * Slice variation for *TeamSection*
 */
type TeamSectionSliceVariation = TeamSectionSliceDefault;

/**
 * TeamSection Shared Slice
 *
 * - **API ID**: `team_section`
 * - **Description**: TeamSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TeamSectionSlice = prismic.SharedSlice<
  "team_section",
  TeamSectionSliceVariation
>;

/**
 * Primary content in *ValuesBlock → Default → Primary*
 */
export interface ValuesBlockSliceDefaultPrimary {
  /**
   * Background field in *ValuesBlock → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Ввести цвет фона
   * - **Default Value**: Main (white)
   * - **API ID Path**: values_block.default.primary.background
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  background: prismic.SelectField<
    "Main (white)" | "Secondary (grey)",
    "filled"
  >;
}

/**
 * Primary content in *ValuesBlock → Items*
 */
export interface ValuesBlockSliceDefaultItem {
  /**
   * Title field in *ValuesBlock → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Служение
   * - **API ID Path**: values_block.items[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *ValuesBlock → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Возможности для миссии и благовестия...
   * - **API ID Path**: values_block.items[].description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;
}

/**
 * Default variation for ValuesBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ValuesBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ValuesBlockSliceDefaultPrimary>,
  Simplify<ValuesBlockSliceDefaultItem>
>;

/**
 * Slice variation for *ValuesBlock*
 */
type ValuesBlockSliceVariation = ValuesBlockSliceDefault;

/**
 * ValuesBlock Shared Slice
 *
 * - **API ID**: `values_block`
 * - **Description**: ValuesBlock
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ValuesBlockSlice = prismic.SharedSlice<
  "values_block",
  ValuesBlockSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ArticleDocument,
      ArticleDocumentData,
      ArticleDocumentDataTagsItem,
      ArticleDocumentDataSlicesSlice,
      ArticlelandingpageDocument,
      ArticlelandingpageDocumentData,
      ArticlelandingpageDocumentDataSlicesSlice,
      AuthorDocument,
      AuthorDocumentData,
      BookDocument,
      BookDocumentData,
      BookDocumentDataTagsItem,
      BooklandingpageDocument,
      BooklandingpageDocumentData,
      BooklandingpageDocumentDataSlicesSlice,
      CommunityDocument,
      CommunityDocumentData,
      CommunityDocumentDataSlicesSlice,
      CommunitylandingpageDocument,
      CommunitylandingpageDocumentData,
      CommunitylandingpageDocumentDataSlicesSlice,
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataNavigationLinksItem,
      FooterDocumentDataActionLinksItem,
      FooterDocumentDataServiceTimesItem,
      FooterDocumentDataSocialLinksItem,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      LandingpageDocument,
      LandingpageDocumentData,
      LandingpageDocumentDataSlicesSlice,
      NavigationDocument,
      NavigationDocumentData,
      NavigationDocumentDataDropdownItemsItem,
      NewspaperDocument,
      NewspaperDocumentData,
      NewspaperDocumentDataTagsItem,
      NewspaperlandingpageDocument,
      NewspaperlandingpageDocumentData,
      NewspaperlandingpageDocumentDataSlicesSlice,
      PodcastDocument,
      PodcastDocumentData,
      PodcastDocumentDataTagsItem,
      PodcastlandingpageDocument,
      PodcastlandingpageDocumentData,
      PodcastlandingpageDocumentDataSlicesSlice,
      TagDocument,
      TagDocumentData,
      TorahlandingpageDocument,
      TorahlandingpageDocumentData,
      TorahlandingpageDocumentDataSlicesSlice,
      VideoDocument,
      VideoDocumentData,
      VideoDocumentDataTagsItem,
      VideolandingpageDocument,
      VideolandingpageDocumentData,
      VideolandingpageDocumentDataSlicesSlice,
      AllDocumentTypes,
      BannerSlice,
      BannerSliceDefaultPrimary,
      BannerSliceVariation,
      BannerSliceDefault,
      BigEventSlice,
      BigEventSliceDefaultPrimary,
      BigEventSliceVariation,
      BigEventSliceDefault,
      CardSlice,
      CardSliceDefaultPrimary,
      CardSliceDefaultItem,
      CardSliceVariation,
      CardSliceDefault,
      FormSlice,
      FormSliceVariation,
      FormSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      HistoryEventsSlice,
      HistoryEventsSliceDefaultPrimary,
      HistoryEventsSliceDefaultItem,
      HistoryEventsSliceVariation,
      HistoryEventsSliceDefault,
      InfoCardSlice,
      InfoCardSliceDefaultItem,
      InfoCardSliceVariation,
      InfoCardSliceDefault,
      LandingPageHeroSlice,
      LandingPageHeroSliceDefaultPrimary,
      LandingPageHeroSliceVariation,
      LandingPageHeroSliceDefault,
      NoteBannerSlice,
      NoteBannerSliceDefaultPrimary,
      NoteBannerSliceDefaultItem,
      NoteBannerSliceVariation,
      NoteBannerSliceDefault,
      QaSlice,
      QaSliceDefaultPrimary,
      QaSliceDefaultItem,
      QaSliceVariation,
      QaSliceDefault,
      SubscribeToNewsletterSlice,
      SubscribeToNewsletterSliceDefaultPrimary,
      SubscribeToNewsletterSliceVariation,
      SubscribeToNewsletterSliceDefault,
      TeamSectionSlice,
      TeamSectionSliceDefaultPrimary,
      TeamSectionSliceDefaultItem,
      TeamSectionSliceVariation,
      TeamSectionSliceDefault,
      ValuesBlockSlice,
      ValuesBlockSliceDefaultPrimary,
      ValuesBlockSliceDefaultItem,
      ValuesBlockSliceVariation,
      ValuesBlockSliceDefault,
    };
  }
}
