// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

interface FooterDocumentData {}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

type HomeDocumentDataSlicesSlice =
  | ValuesBlockSlice
  | SubscribeToNewsletterSlice
  | NoteBannerSlice
  | QaSlice
  | InfoCardSlice
  | CardSlice
  | BigEventSlice
  | HeroSlice
  | FormSlice
  | BannerSlice;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice>; /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

type LandingpageDocumentDataSlicesSlice =
  | InfoCardSlice
  | QaSlice
  | SubscribeToNewsletterSlice
  | ValuesBlockSlice
  | FormSlice
  | BannerSlice
  | BigEventSlice
  | CardSlice
  | LandingPageHeroSlice
  | NoteBannerSlice;

/**
 * Content for LandingPage documents
 */
interface LandingpageDocumentData {
  /**
   * Slice Zone field in *LandingPage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: landingpage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<LandingpageDocumentDataSlicesSlice>; /**
   * Meta Title field in *LandingPage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: landingpage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *LandingPage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: landingpage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *LandingPage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: landingpage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * LandingPage document from Prismic
 *
 * - **API ID**: `landingpage`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LandingpageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<LandingpageDocumentData>,
    "landingpage",
    Lang
  >;

/**
 * Item in *Header → Links*
 */
export interface NavigationDocumentDataLinksItem {
  /**
   * Label field in *Header → Links*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Optional - Label for the link
   * - **API ID Path**: navigation.links[].label
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  label: prismic.RichTextField;

  /**
   * Link field in *Header → Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link for navigation item
   * - **API ID Path**: navigation.links[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Item in *Header → Dropdown items*
 */
export interface NavigationDocumentDataDropdownItemsItem {
  /**
   * Label field in *Header → Dropdown items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Label for dropdown item
   * - **API ID Path**: navigation.dropdown_items[].label
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  label: prismic.RichTextField;

  /**
   * Link field in *Header → Dropdown items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link for dropdown item
   * - **API ID Path**: navigation.dropdown_items[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Icon field in *Header → Dropdown items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Select an icon
   * - **API ID Path**: navigation.dropdown_items[].icon
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  icon: prismic.SelectField<
    "Video" | "Mic" | "FileText" | "BookMarked" | "Radio" | "Newspaper"
  >;
}

/**
 * Content for Header documents
 */
interface NavigationDocumentData {
  /**
   * Logo field in *Header*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;

  /**
   * Links field in *Header*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  links: prismic.GroupField<Simplify<NavigationDocumentDataLinksItem>>;

  /**
   * Dropdown label field in *Header*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Optional - Label for the dropdown
   * - **API ID Path**: navigation.dropdown_label
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  dropdown_label: prismic.RichTextField;

  /**
   * Dropdown link field in *Header*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link for the dropdown
   * - **API ID Path**: navigation.dropdown_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  dropdown_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Dropdown items field in *Header*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.dropdown_items[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  dropdown_items: prismic.GroupField<
    Simplify<NavigationDocumentDataDropdownItemsItem>
  >;

  /**
   * Primary button label field in *Header*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Label for primary action
   * - **API ID Path**: navigation.action_button_primary_label
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  action_button_primary_label: prismic.RichTextField;

  /**
   * Primary button link field in *Header*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link for primary action
   * - **API ID Path**: navigation.action_button_primary_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  action_button_primary_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Primary button variant field in *Header*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Choose a button style
   * - **API ID Path**: navigation.action_button_primary_variant
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  action_button_primary_variant: prismic.SelectField<
    "primary" | "secondary" | "ghost" | "outline" | "filled"
  >;

  /**
   * Secondary button label field in *Header*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Label for secondary action
   * - **API ID Path**: navigation.action_button_secondary_label
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  action_button_secondary_label: prismic.RichTextField;

  /**
   * Secondary button link field in *Header*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link for secondary action
   * - **API ID Path**: navigation.action_button_secondary_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  action_button_secondary_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Secondary button variant field in *Header*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Choose a button style
   * - **API ID Path**: navigation.action_button_secondary_variant
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  action_button_secondary_variant: prismic.SelectField<
    "primary" | "secondary" | "ghost" | "outline" | "filled"
  >;
}

/**
 * Header document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavigationDocumentData>,
    "navigation",
    Lang
  >;

export type AllDocumentTypes =
  | FooterDocument
  | HomeDocument
  | LandingpageDocument
  | NavigationDocument;

/**
 * Primary content in *Banner → Default → Primary*
 */
export interface BannerSliceDefaultPrimary {
  /**
   * Title field in *Banner → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Добро пожаловать
   * - **API ID Path**: banner.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Banner → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Короткое приглашение или сообщение
   * - **API ID Path**: banner.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * Button Text field in *Banner → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Узнать больше
   * - **API ID Path**: banner.default.primary.actionLabel
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  actionLabel: prismic.KeyTextField;

  /**
   * Button Link field in *Banner → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: https://example.com
   * - **API ID Path**: banner.default.primary.actionLink
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  actionLink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Background Image field in *Banner → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for Banner Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BannerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BannerSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Banner*
 */
type BannerSliceVariation = BannerSliceDefault;

/**
 * Banner Shared Slice
 *
 * - **API ID**: `banner`
 * - **Description**: Banner
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BannerSlice = prismic.SharedSlice<"banner", BannerSliceVariation>;

/**
 * Primary content in *BigEvent → Default → Primary*
 */
export interface BigEventSliceDefaultPrimary {
  /**
   * Label field in *BigEvent → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Следующее событие
   * - **API ID Path**: big_event.default.primary.label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Title field in *BigEvent → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Миссионерская конференция
   * - **API ID Path**: big_event.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Summary field in *BigEvent → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Короткое описание события
   * - **API ID Path**: big_event.default.primary.summary
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  summary: prismic.KeyTextField;

  /**
   * Date display field in *BigEvent → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: 25 апреля 2026
   * - **API ID Path**: big_event.default.primary.date
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  date: prismic.KeyTextField;

  /**
   * Time field in *BigEvent → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: 10:00
   * - **API ID Path**: big_event.default.primary.time
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  time: prismic.KeyTextField;

  /**
   * Location field in *BigEvent → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Москва, ул. Пример, 1
   * - **API ID Path**: big_event.default.primary.location
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  location: prismic.KeyTextField;

  /**
   * Countdown target field in *BigEvent → Default → Primary*
   *
   * - **Field Type**: Timestamp
   * - **Placeholder**: 2026-04-25T10:00:00+03:00
   * - **API ID Path**: big_event.default.primary.countdownTarget
   * - **Documentation**: https://prismic.io/docs/fields/timestamp
   */
  countdownTarget: prismic.TimestampField;

  /**
   * Background image field in *BigEvent → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: big_event.default.primary.backgroundImage
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  backgroundImage: prismic.ImageField<never>;

  /**
   * Primary button text field in *BigEvent → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Зарегистрироваться
   * - **API ID Path**: big_event.default.primary.primaryButtonText
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  primaryButtonText: prismic.KeyTextField;

  /**
   * Primary button link field in *BigEvent → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: big_event.default.primary.primaryButtonLink
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  primaryButtonLink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Secondary button text field in *BigEvent → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Подробнее
   * - **API ID Path**: big_event.default.primary.secondaryButtonText
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  secondaryButtonText: prismic.KeyTextField;

  /**
   * Secondary button link field in *BigEvent → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: big_event.default.primary.secondaryButtonLink
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  secondaryButtonLink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for BigEvent Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BigEventSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BigEventSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BigEvent*
 */
type BigEventSliceVariation = BigEventSliceDefault;

/**
 * BigEvent Shared Slice
 *
 * - **API ID**: `big_event`
 * - **Description**: BigEvent
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BigEventSlice = prismic.SharedSlice<
  "big_event",
  BigEventSliceVariation
>;

/**
 * Primary content in *Card → Default → Primary*
 */
export interface CardSliceDefaultPrimary {
  /**
   * Label field in *Card → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Миссия
   * - **API ID Path**: card.default.primary.label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Title field in *Card → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Во что мы верим
   * - **API ID Path**: card.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Card → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Краткое описание блока
   * - **API ID Path**: card.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;
}

/**
 * Primary content in *Card → Items*
 */
export interface CardSliceDefaultItem {
  /**
   * Highlight text (optional) field in *Card → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Короткая цитата/выдержка
   * - **API ID Path**: card.items[].description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * Title field in *Card → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Заголовок карточки
   * - **API ID Path**: card.items[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Body field in *Card → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Основное описание
   * - **API ID Path**: card.items[].body
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  body: prismic.KeyTextField;

  /**
   * Image field in *Card → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: card.items[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Button label field in *Card → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Узнать больше
   * - **API ID Path**: card.items[].buttonLabel
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  buttonLabel: prismic.KeyTextField;

  /**
   * Button link field in *Card → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: https://example.com
   * - **API ID Path**: card.items[].buttonLink
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  buttonLink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for Card Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CardSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CardSliceDefaultPrimary>,
  Simplify<CardSliceDefaultItem>
>;

/**
 * Slice variation for *Card*
 */
type CardSliceVariation = CardSliceDefault;

/**
 * Card Shared Slice
 *
 * - **API ID**: `card`
 * - **Description**: Card
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CardSlice = prismic.SharedSlice<"card", CardSliceVariation>;

/**
 * Default variation for Form Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FormSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Form*
 */
type FormSliceVariation = FormSliceDefault;

/**
 * Form Shared Slice
 *
 * - **API ID**: `form`
 * - **Description**: Form
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FormSlice = prismic.SharedSlice<"form", FormSliceVariation>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Title field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Text field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;

  /**
   * Button Link field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.buttonLink
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  buttonLink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Button Text field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.buttonText
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  buttonText: prismic.KeyTextField;

  /**
   * Secondary Button Link field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.secondaryButtonLink
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  secondaryButtonLink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Secondary Button Text field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.secondaryButtonText
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  secondaryButtonText: prismic.KeyTextField;

  /**
   * Video Embed field in *Hero → Default → Primary*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: YouTube/Vimeo embed
   * - **API ID Path**: hero.default.primary.videoEmbed
   * - **Documentation**: https://prismic.io/docs/fields/embed
   */
  videoEmbed: prismic.EmbedField;

  /**
   * Background Image field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.backgroundImage
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  backgroundImage: prismic.ImageField<never>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *InfoCard → Items*
 */
export interface InfoCardSliceDefaultItem {
  /**
   * Icon field in *InfoCard → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: ✦
   * - **API ID Path**: info_card.items[].icon
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  icon: prismic.KeyTextField;

  /**
   * Title field in *InfoCard → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Заголовок
   * - **API ID Path**: info_card.items[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Text field in *InfoCard → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Краткое описание
   * - **API ID Path**: info_card.items[].text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  text: prismic.KeyTextField;

  /**
   * Button label field in *InfoCard → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Подробнее
   * - **API ID Path**: info_card.items[].buttonLabel
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  buttonLabel: prismic.KeyTextField;

  /**
   * Button link field in *InfoCard → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: https://example.com
   * - **API ID Path**: info_card.items[].buttonLink
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  buttonLink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Button variant field in *InfoCard → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: secondary
   * - **API ID Path**: info_card.items[].buttonVariant
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  buttonVariant: prismic.SelectField<"secondary" | "ghost", "filled">;

  /**
   * Button target field in *InfoCard → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: _self
   * - **API ID Path**: info_card.items[].buttonTarget
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  buttonTarget: prismic.SelectField<"_self" | "_blank", "filled">;
}

/**
 * Default variation for InfoCard Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type InfoCardSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<InfoCardSliceDefaultItem>
>;

/**
 * Slice variation for *InfoCard*
 */
type InfoCardSliceVariation = InfoCardSliceDefault;

/**
 * InfoCard Shared Slice
 *
 * - **API ID**: `info_card`
 * - **Description**: InfoCard
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type InfoCardSlice = prismic.SharedSlice<
  "info_card",
  InfoCardSliceVariation
>;

/**
 * Primary content in *LandingPageHero → Default → Primary*
 */
export interface LandingPageHeroSliceDefaultPrimary {
  /**
   * Title field in *LandingPageHero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: О нас
   * - **API ID Path**: landing_page_hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *LandingPageHero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Краткое описание секции (Rich Text)
   * - **API ID Path**: landing_page_hero.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Background image field in *LandingPageHero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: landing_page_hero.default.primary.backgroundImage
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  backgroundImage: prismic.ImageField<never>;

  /**
   * Breadcrumb home label field in *LandingPageHero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Главная
   * - **API ID Path**: landing_page_hero.default.primary.breadcrumbHomeLabel
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  breadcrumbHomeLabel: prismic.KeyTextField;

  /**
   * Breadcrumb home link field in *LandingPageHero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: /
   * - **API ID Path**: landing_page_hero.default.primary.breadcrumbHomeLink
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  breadcrumbHomeLink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Breadcrumb current field in *LandingPageHero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: О нас
   * - **API ID Path**: landing_page_hero.default.primary.breadcrumbCurrent
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  breadcrumbCurrent: prismic.KeyTextField;

  /**
   * Button label (optional) field in *LandingPageHero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Подробнее
   * - **API ID Path**: landing_page_hero.default.primary.buttonLabel
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  buttonLabel: prismic.KeyTextField;

  /**
   * Button link (optional) field in *LandingPageHero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: https://example.com
   * - **API ID Path**: landing_page_hero.default.primary.buttonLink
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  buttonLink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for LandingPageHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LandingPageHeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LandingPageHeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *LandingPageHero*
 */
type LandingPageHeroSliceVariation = LandingPageHeroSliceDefault;

/**
 * LandingPageHero Shared Slice
 *
 * - **API ID**: `landing_page_hero`
 * - **Description**: LandingPageHero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LandingPageHeroSlice = prismic.SharedSlice<
  "landing_page_hero",
  LandingPageHeroSliceVariation
>;

/**
 * Primary content in *NoteBanner → Default → Primary*
 */
export interface NoteBannerSliceDefaultPrimary {
  /**
   * Label field in *NoteBanner → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Слово президента
   * - **API ID Path**: note_banner.default.primary.label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Name field in *NoteBanner → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: President name
   * - **API ID Path**: note_banner.default.primary.name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Title field in *NoteBanner → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: President title
   * - **API ID Path**: note_banner.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Photo field in *NoteBanner → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: note_banner.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Signature field in *NoteBanner → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Optional closing line
   * - **API ID Path**: note_banner.default.primary.signature
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  signature: prismic.KeyTextField;

  /**
   * Button Text field in *NoteBanner → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Read more
   * - **API ID Path**: note_banner.default.primary.buttonText
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  buttonText: prismic.KeyTextField;

  /**
   * Button Link field in *NoteBanner → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: note_banner.default.primary.buttonLink
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  buttonLink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *NoteBanner → Items*
 */
export interface NoteBannerSliceDefaultItem {
  /**
   * Paragraph field in *NoteBanner → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Message paragraph
   * - **API ID Path**: note_banner.items[].paragraph
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  paragraph: prismic.KeyTextField;
}

/**
 * Default variation for NoteBanner Slice
 *
 * - **API ID**: `default`
 * - **Description**: President note banner with portrait, message, and CTA
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type NoteBannerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NoteBannerSliceDefaultPrimary>,
  Simplify<NoteBannerSliceDefaultItem>
>;

/**
 * Slice variation for *NoteBanner*
 */
type NoteBannerSliceVariation = NoteBannerSliceDefault;

/**
 * NoteBanner Shared Slice
 *
 * - **API ID**: `note_banner`
 * - **Description**: NoteBanner
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type NoteBannerSlice = prismic.SharedSlice<
  "note_banner",
  NoteBannerSliceVariation
>;

/**
 * Primary content in *Qa → Default → Primary*
 */
export interface QaSliceDefaultPrimary {
  /**
   * Title field in *Qa → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Частые вопросы
   * - **API ID Path**: qa.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Qa → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Ответы на самые популярные вопросы
   * - **API ID Path**: qa.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;
}

/**
 * Primary content in *Qa → Items*
 */
export interface QaSliceDefaultItem {
  /**
   * Question field in *Qa → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Как проходит ваше служение?
   * - **API ID Path**: qa.items[].question
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  question: prismic.KeyTextField;

  /**
   * Answer field in *Qa → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Мы собираемся каждое воскресенье...
   * - **API ID Path**: qa.items[].answer
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  answer: prismic.KeyTextField;
}

/**
 * Default variation for Qa Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type QaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<QaSliceDefaultPrimary>,
  Simplify<QaSliceDefaultItem>
>;

/**
 * Slice variation for *Qa*
 */
type QaSliceVariation = QaSliceDefault;

/**
 * Qa Shared Slice
 *
 * - **API ID**: `qa`
 * - **Description**: Qa
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type QaSlice = prismic.SharedSlice<"qa", QaSliceVariation>;

/**
 * Primary content in *SubscribeToNewsletter → Default → Primary*
 */
export interface SubscribeToNewsletterSliceDefaultPrimary {
  /**
   * Title field in *SubscribeToNewsletter → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Подпишитесь на рассылку
   * - **API ID Path**: subscribe_to_newsletter.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *SubscribeToNewsletter → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Будьте в курсе наших последних новостей и событий...
   * - **API ID Path**: subscribe_to_newsletter.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * Background image field in *SubscribeToNewsletter → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: subscribe_to_newsletter.default.primary.backgroundImage
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  backgroundImage: prismic.ImageField<never>;

  /**
   * Button text field in *SubscribeToNewsletter → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Подписаться
   * - **API ID Path**: subscribe_to_newsletter.default.primary.buttonText
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  buttonText: prismic.KeyTextField;
}

/**
 * Default variation for SubscribeToNewsletter Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SubscribeToNewsletterSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SubscribeToNewsletterSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SubscribeToNewsletter*
 */
type SubscribeToNewsletterSliceVariation = SubscribeToNewsletterSliceDefault;

/**
 * SubscribeToNewsletter Shared Slice
 *
 * - **API ID**: `subscribe_to_newsletter`
 * - **Description**: SubscribeToNewsletter
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SubscribeToNewsletterSlice = prismic.SharedSlice<
  "subscribe_to_newsletter",
  SubscribeToNewsletterSliceVariation
>;

/**
 * Primary content in *ValuesBlock → Items*
 */
export interface ValuesBlockSliceDefaultItem {
  /**
   * Title field in *ValuesBlock → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Служение
   * - **API ID Path**: values_block.items[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *ValuesBlock → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Возможности для миссии и благовестия...
   * - **API ID Path**: values_block.items[].description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;
}

/**
 * Default variation for ValuesBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ValuesBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<ValuesBlockSliceDefaultItem>
>;

/**
 * Slice variation for *ValuesBlock*
 */
type ValuesBlockSliceVariation = ValuesBlockSliceDefault;

/**
 * ValuesBlock Shared Slice
 *
 * - **API ID**: `values_block`
 * - **Description**: ValuesBlock
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ValuesBlockSlice = prismic.SharedSlice<
  "values_block",
  ValuesBlockSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      FooterDocument,
      FooterDocumentData,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      LandingpageDocument,
      LandingpageDocumentData,
      LandingpageDocumentDataSlicesSlice,
      NavigationDocument,
      NavigationDocumentData,
      NavigationDocumentDataLinksItem,
      NavigationDocumentDataDropdownItemsItem,
      AllDocumentTypes,
      BannerSlice,
      BannerSliceDefaultPrimary,
      BannerSliceVariation,
      BannerSliceDefault,
      BigEventSlice,
      BigEventSliceDefaultPrimary,
      BigEventSliceVariation,
      BigEventSliceDefault,
      CardSlice,
      CardSliceDefaultPrimary,
      CardSliceDefaultItem,
      CardSliceVariation,
      CardSliceDefault,
      FormSlice,
      FormSliceVariation,
      FormSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      InfoCardSlice,
      InfoCardSliceDefaultItem,
      InfoCardSliceVariation,
      InfoCardSliceDefault,
      LandingPageHeroSlice,
      LandingPageHeroSliceDefaultPrimary,
      LandingPageHeroSliceVariation,
      LandingPageHeroSliceDefault,
      NoteBannerSlice,
      NoteBannerSliceDefaultPrimary,
      NoteBannerSliceDefaultItem,
      NoteBannerSliceVariation,
      NoteBannerSliceDefault,
      QaSlice,
      QaSliceDefaultPrimary,
      QaSliceDefaultItem,
      QaSliceVariation,
      QaSliceDefault,
      SubscribeToNewsletterSlice,
      SubscribeToNewsletterSliceDefaultPrimary,
      SubscribeToNewsletterSliceVariation,
      SubscribeToNewsletterSliceDefault,
      ValuesBlockSlice,
      ValuesBlockSliceDefaultItem,
      ValuesBlockSliceVariation,
      ValuesBlockSliceDefault,
    };
  }
}
