// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  banner: dynamic(() => import("./Banner")),
  big_event: dynamic(() => import("./BigEvent")),
  card: dynamic(() => import("./Card")),
  form: dynamic(() => import("./Form")),
  hero: dynamic(() => import("./Hero")),
  history_events: dynamic(() => import("./HistoryEvents")),
  info_card: dynamic(() => import("./InfoCard")),
  landing_page_hero: dynamic(() => import("./LandingPageHero")),
  note_banner: dynamic(() => import("./NoteBanner")),
  podcast_carousel: dynamic(() => import("./PodcastCarousel")),
  qa: dynamic(() => import("./Qa")),
  subscribe_to_newsletter: dynamic(() => import("./SubscribeToNewsletter")),
  team_section: dynamic(() => import("./TeamSection")),
  values_block: dynamic(() => import("./ValuesBlock")),
  video_carousel: dynamic(() => import("./VideoCarousel")),
};
